// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"container py-2 z-30 mb-4 lg:mt-4 lg:rounded-lg glass\"><nav class=\"relative flex flex-wrap items-center justify-between\"><!-- Navbar toggler --><input id=\"nav-toggle\" type=\"checkbox\" class=\"hidden\"> <label for=\"nav-toggle\" class=\"order-0 cursor-pointer flex items-center md:hidden text-gray-700 lg:order-1\"><svg id=\"show-button\" class=\"h-6 fill-current block\" viewBox=\"0 0 20 20\"><title>Menu Open</title><path d=\"M0 3h20v2H0V3z m0 6h20v2H0V9z m0 6h20v2H0V0z\"></path></svg></label><!-- /Navbar toggler --><ul id=\"nav-menu\" class=\"text-center lg:text-left order-3 hidden w-full pb-6 md:order-1 md:flex md:w-auto md:space-x-2 md:pb-0 lg:space-x-4\"><li><a href=\"/\" class=\"block p-2 font-semibold text-gray-700 dlg:px-2 lg:py-3\">Home</a></li><li><a href=\"/#\" class=\"block p-2 font-semibold text-gray-700 lg:px-2 lg:py-3\">About</a></li><li><a href=\"/#\" class=\"block p-2 font-semibold text-gray-700 lg:px-2 lg:py-3\">Docs</a></li></ul><div class=\"order-1 ml-auto flex items-center md:order-2 lg:ml-0\"><a class=\"mr-4 inline-block text-xl text-gray-700\" href=\"/#\" aria-label=\"search\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-4.35-4.35m0 0a7.5 7.5 0 111.06-1.06l4.35 4.35z\"></path></svg></a></div></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
